### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by steventeague** [wowmaking/react-native-unity#27]
hey guys Sure i'm missing something simple here but can't seem to resolve this issue

when it tries to compile the unity framework I get this .... ? RNUProxy builds fine and I see the plugins in the ios plugin folder but yet it won't build.. suggestions welcome :-) thanks

Undefined symbols for architecture arm64:
  "_sendMessage", referenced from:
      _NativeAPI_sendMessage_mF21F064E2FED9923050295578F747882F4DC1917 in Wowmaking.RNU.o
     (maybe you meant: _NativeAPI_sendMessage_mF21F064E2FED9923050295578F747882F4DC1917)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hazelWolf** [comment]
Try exporting Unity android project as ILCPP instead of mono and select ARMv7 and ARM64 in player settings and then export. Works on Unity 2019.3 and  above.
